import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.equipment': 'Equipment',
    'nav.orders': 'Orders',
    'nav.forum': 'Forum',
    'nav.lending': 'Lending',
    'nav.expenses': 'Expenses',
    'nav.insights': 'Insights',
    'nav.schemes': 'Schemes',
    'nav.banking': 'Banking',
    'nav.location': 'Location',
    
    // Header
    'header.cart': 'Cart',
    'header.signIn': 'Sign In',
    'header.signUp': 'Sign Up',
    'header.language': 'Language',
    
    // Dashboard
    'dashboard.title': 'Welcome to AgroConnect',
    'dashboard.subtitle': 'Empowering Tamil Nadu Farmers',
    'dashboard.equipment.title': 'Modern Equipment',
    'dashboard.equipment.subtitle': 'Rent high-quality farming equipment',
    'dashboard.lending.title': 'Micro Lending',
    'dashboard.lending.subtitle': 'Community-based lending circles',
    'dashboard.forum.title': 'Community Forum',
    'dashboard.forum.subtitle': 'Connect with fellow farmers',
    'dashboard.expenses.title': 'Expense Tracker',
    'dashboard.expenses.subtitle': 'Track your farming costs',
    'dashboard.insights.title': 'AI Insights',
    'dashboard.insights.subtitle': 'Smart farming recommendations',
    'dashboard.schemes.title': 'Government Schemes',
    'dashboard.schemes.subtitle': 'Access Tamil Nadu schemes',
    'dashboard.banking.title': 'Banking Services',
    'dashboard.banking.subtitle': 'Agricultural loans and insurance',
    'dashboard.stats.totalExpenses': 'Total Expenses',
    'dashboard.stats.activeLoans': 'Active Loans',
    'dashboard.stats.equipmentBookings': 'Equipment Bookings',
    'dashboard.stats.forumPosts': 'Forum Posts',
    'dashboard.stats.expensesTrend': '12% from last month',
    'dashboard.stats.loansTrend': '2 approved this week',
    'dashboard.stats.equipmentTrend': 'Next: Tomorrow 9 AM',
    'dashboard.stats.forumTrend': '5 new this week',
    'dashboard.actions.bookEquipment': 'Book Equipment',
    'dashboard.actions.bookEquipmentDesc': 'Reserve tractors, harvesters, and more',
    'dashboard.actions.joinForum': 'Join Forum',
    'dashboard.actions.joinForumDesc': 'Connect with fellow farmers',
    'dashboard.actions.trackExpenses': 'Track Expenses',
    'dashboard.actions.trackExpensesDesc': 'Monitor your farming costs',
    'dashboard.actions.viewSchemes': 'View Schemes',
    'dashboard.actions.viewSchemesDesc': 'Access government programs',
    
    // Dashboard additional content
    'dashboard.stats.title': 'Quick Stats',
    'dashboard.quickActions.title': 'Quick Actions',
    'dashboard.recentActivity.title': 'Recent Activity',
    'dashboard.getStarted': 'Get Started',
    'dashboard.premium': 'PREMIUM',
    'dashboard.instant': 'INSTANT',
    'dashboard.organic': 'ORGANIC',
    'dashboard.smart': 'SMART',
    'dashboard.active': 'ACTIVE',
    'dashboard.secure': 'SECURE',
    'dashboard.fromPrice': 'From ₹2,500/day',
    'dashboard.upToPrice': 'Up to ₹50,000',
    'dashboard.upToOff': 'Up to 30% Off',
    'dashboard.liveData': 'Live Data',
    'dashboard.members': '15,000+ Members',
    'dashboard.insurancePrice': 'From ₹500/year',
    
    // Recent activity
    'dashboard.activity.tractorBooked': 'Tractor booked for tomorrow',
    'dashboard.activity.loanApproved': 'Loan approved - ₹15,000',
    'dashboard.activity.forumReply': 'New forum reply on pest control',
    'dashboard.activity.fertilizerOrder': 'Fertilizer order completed',
    'dashboard.activity.hoursAgo': 'hours ago',
    'dashboard.activity.dayAgo': 'day ago',
    'dashboard.activity.daysAgo': 'days ago',
    
    // Schemes
    'schemes.title': 'Government Schemes',
    'schemes.subtitle': 'Tamil Nadu Farmer Schemes & Benefits',
    'schemes.search': 'Search schemes...',
    'schemes.filterByCategory': 'Filter by Category',
    'schemes.filterByCaste': 'Filter by Caste',
    'schemes.allCategories': 'All Categories',
    'schemes.allCastes': 'All Castes',
    'schemes.viewDetails': 'View Details',
    'schemes.applyNow': 'Apply Now',
    'schemes.benefits': 'Benefits',
    'schemes.eligibility': 'Eligibility',
    'schemes.applicationProcess': 'Application Process',
    'schemes.contact': 'Contact',
    'schemes.directBenefits': 'Direct Benefits',
    'schemes.categories.general': 'General',
    'schemes.categories.financial': 'Financial',
    'schemes.categories.agricultural': 'Agricultural',
    'schemes.categories.insurance': 'Insurance',
    'schemes.categories.education': 'Education',
    'schemes.categories.healthcare': 'Healthcare',
    'schemes.categories.women': 'Women',
    'schemes.categories.youth': 'Youth',
    'schemes.categories.senior': 'Senior Citizens',
    'schemes.categories.disabled': 'Disabled',
    'schemes.categories.welfare': 'Welfare',
    'schemes.categories.development': 'Development',
    'schemes.categories.irrigation': 'Irrigation',
    'schemes.categories.equipment': 'Equipment',
    'schemes.categories.infrastructure': 'Infrastructure',
    'schemes.categories.training': 'Training',
    'schemes.categories.utility': 'Utility',
    'schemes.categories.tribal': 'Tribal',
    'schemes.castes.sc': 'Scheduled Caste',
    'schemes.castes.st': 'Scheduled Tribe',
    'schemes.castes.obc': 'Other Backward Class',
    'schemes.castes.mbc': 'Most Backward Class',
    'schemes.castes.general': 'General',
    'schemes.castes.minority': 'Minority',
    'schemes.selectCommunity': 'Select Your Community',
    'schemes.selectCommunityDesc': 'Choose your community to see personalized schemes along with general schemes available to all farmers',
    'schemes.generalSchemesNote': 'Note: You can also browse general schemes available to all farmers below without selecting a community.',
    'schemes.changeCommunity': 'Change Community',
    'schemes.noSchemesFound': 'No schemes found',
    'schemes.noSchemesFoundDesc': 'Try adjusting your search terms or category filter',
    'schemes.howToApply': 'How to Apply for TamilNadu Farmer Schemes',
    'schemes.howToApplyDesc': 'Follow these simple steps to find and apply for Tamil Nadu farmer schemes',
    'schemes.step1.title': 'Browse Schemes',
    'schemes.step1.desc1': 'Select your community from the options above',
    'schemes.step1.desc2': 'Use the search bar to find specific schemes',
    'schemes.step1.desc3': 'Filter by category (Agriculture, Insurance, etc.)',
    'schemes.step1.desc4': 'Read scheme details and benefits',
    'schemes.step2.title': 'Check Requirements',
    'schemes.step2.desc1': 'Review eligibility criteria for each scheme',
    'schemes.step2.desc2': 'Ensure you have required documents',
    'schemes.step2.desc3': 'Check land records and certificates',
    'schemes.step2.desc4': 'Verify age and community requirements',
    'schemes.step3.title': 'Apply Online',
    'schemes.step3.desc1': 'Visit Tamil Nadu e-Sevai portal',
    'schemes.step3.desc2': 'Create your farmer account',
    'schemes.step3.desc3': 'Fill application forms with required details',
    'schemes.step3.desc4': 'Upload necessary documents',
    'schemes.step4.title': 'Track Application',
    'schemes.step4.desc1': 'Check application status online',
    'schemes.step4.desc2': 'Receive SMS updates on your mobile',
    'schemes.step4.desc3': 'Visit nearest e-Sevai center if needed',
    'schemes.step4.desc4': 'Follow up with department officials',
    'schemes.quickLinks': 'Quick Links',
    'schemes.eSevaiPortal': 'Tamil Nadu e-Sevai Portal',
    'schemes.helpline': 'Helpline: 1800-425-1556',
    'schemes.agricultureDepartment': 'Agriculture Department',
    'schemes.howToApplyTractor': 'How to Apply for Free Tractor',
    'schemes.top5Schemes': 'Top 5 Schemes for Farmers',
    'schemes.note': 'Note:',
    'schemes.noteText': 'All schemes are subject to government guidelines and eligibility criteria.',
    'schemes.verifyInfo': 'Please verify the latest information from official Tamil Nadu government sources.',
    
    // Scheme titles
    'schemes.cmFarmersProtection.title': "Chief Minister's Farmers Protection Scheme",
    'schemes.summerPloughing.title': 'Summer Ploughing Incentive',
    'schemes.wellRenovation.title': 'Well Renovation Subsidy (Pilot)',
    'schemes.naturalFarming.title': 'Natural Farming Scheme',
    'schemes.hillFarmers.title': 'Hill Farmers Development Scheme',
    'schemes.sugarcanePrice.title': 'Sugarcane Price Incentive',
    'schemes.cropInsurance.title': 'Crop Insurance Subsidy',
    'schemes.paddyProcurement.title': 'Paddy Procurement MSP + Incentive',
    'schemes.agriMachinery.title': 'Agri Machinery Subsidy',
    'schemes.cmServiceCentres.title': "Chief Minister's Farmers Service Centres",
    'schemes.nutritionFarming.title': 'Nutrition Farming Mission',
    'schemes.internationalExposure.title': 'International Exposure Visits',
    'schemes.electricitySubsidy.title': 'Electricity Subsidy',
    'schemes.scDevelopment.title': 'Scheduled Caste Farmers Development Scheme',
    'schemes.bcDevelopment.title': 'Backward Classes Development Scheme',
    'schemes.mbcAgriculture.title': 'Most Backward Classes Agriculture Scheme',
    'schemes.minorityFarmers.title': 'Minority Farmers Development Scheme',
    'schemes.tribalFarmers.title': 'Tribal Farmers Welfare Scheme',
    'schemes.womenFarmers.title': 'Women Farmers Empowerment Scheme',
    'schemes.youthFarmers.title': 'Youth Farmers Startup Scheme',
    
    // Scheme descriptions
    'schemes.cmFarmersProtection.desc': 'Comprehensive insurance coverage for farmers against natural calamities and crop failures.',
    'schemes.summerPloughing.desc': 'Direct financial incentive for summer ploughing to improve soil health and water retention.',
    'schemes.wellRenovation.desc': 'Financial support for renovating abandoned wells to improve water availability.',
    'schemes.naturalFarming.desc': 'Support for farmers transitioning to natural farming methods.',
    'schemes.hillFarmers.desc': 'Special development programs for farmers in hilly regions.',
    'schemes.sugarcanePrice.desc': 'Direct price incentive for sugarcane farmers above FRP.',
    'schemes.cropInsurance.desc': 'Crop insurance premium fully subsidized for all farmers.',
    'schemes.paddyProcurement.desc': 'State incentive for paddy farmers above government procurement price.',
    'schemes.agriMachinery.desc': '60% subsidy on agricultural machinery and installation assistance.',
    'schemes.cmServiceCentres.desc': 'Chief Minister scheme for establishing service centers for farmers.',
    'schemes.nutritionFarming.desc': 'Free seeds and saplings for growing nutritious crops.',
    'schemes.internationalExposure.desc': 'Fully funded trips for progressive farmers to learn international agricultural techniques.',
    'schemes.electricitySubsidy.desc': 'Subsidy for electricity for agricultural purposes.',
    'schemes.scDevelopment.desc': 'Comprehensive development schemes for Scheduled Caste farmers.',
    'schemes.bcDevelopment.desc': 'Development schemes for Backward Class farmers focusing on modern agricultural practices.',
    'schemes.mbcAgriculture.desc': 'Special agricultural development programs for Most Backward Class farmers.',
    'schemes.minorityFarmers.desc': 'Development schemes for minority community farmers including financial assistance and training.',
    'schemes.tribalFarmers.desc': 'Comprehensive welfare schemes for Scheduled Tribe farmers in tribal areas.',
    'schemes.womenFarmers.desc': 'Special schemes for women farmers focusing on empowerment and financial independence.',
    'schemes.youthFarmers.desc': 'Support for young farmers to start agricultural ventures with modern technology.',
    
    // Common scheme text
    'schemes.allFarmers': 'All farmers',
    'schemes.farmersWithLand': 'Farmers with land records',
    'schemes.registeredFarmers': 'Farmers registered with Agriculture Department',
    'schemes.onlineApplication': 'Online application through Tamil Nadu e-Sevai portal',
    'schemes.agricultureDepartment': 'Agriculture Department',
    'schemes.waterResources': 'Water Resources Department',
    'schemes.hillDevelopment': 'Hill Area Development Agency',
    'schemes.sugarMills': 'Sugar mills',
    'schemes.procurementCenters': 'Procurement centers',
    'schemes.agricultureEngineering': 'Agriculture Engineering Department',
    'schemes.startupMission': 'Startup Mission',
    'schemes.womenDevelopment': 'Women Development Corporation',
    'schemes.tribalWelfare': 'Tribal Welfare Department',
    'schemes.minoritiesCorporation': 'Tamil Nadu Minorities Economic Development Corporation',
    'schemes.mbcCorporation': 'MBC Corporation',
    'schemes.bcWelfare': 'BC Welfare Department',
    'schemes.adiDravidarWelfare': 'District Adi Dravidar Welfare Office',
    
    // Banking
    'banking.title': 'Tamil Nadu Farmers Banking Portal',
    'banking.subtitle': 'Comprehensive banking solutions for farmers across Tamil Nadu',
    'banking.searchBanks': 'Search banks...',
    'banking.findNearbyBranches': 'Find Nearby Branches',
    'banking.getLocation': 'Get My Location',
    'banking.locationError': 'Location information is unavailable',
    'banking.loadingLocation': 'Getting your location...',
    'banking.bankDetails': 'Bank Details',
    'banking.loanSchemes': 'Loan Schemes',
    'banking.branches': 'Branches',
    'banking.contact': 'Contact',
    'banking.website': 'Website',
    'banking.phone': 'Phone',
    'banking.address': 'Address',
    'banking.timings': 'Timings',
    'banking.ifscCode': 'IFSC Code',
    'banking.interestRate': 'Interest Rate',
    'banking.maxAmount': 'Maximum Amount',
    'banking.tenure': 'Tenure',
    'banking.eligibility': 'Eligibility',
    'banking.documents': 'Required Documents',
    'banking.specialFeatures': 'Special Features',
    'banking.eligibilityCriteria': 'Eligibility Criteria',
    'banking.applyNow': 'Apply Now',
    'banking.viewDetails': 'View Details',
    'banking.nearbyBranches': 'Nearby Branches',
    'banking.noBranchesFound': 'No branches found in your area',
    'banking.selectBank': 'Select a bank to view details',
    'banking.selectLoan': 'Select a loan scheme to view details',
    'banking.agriculturalLoans': 'Agricultural Loans',
    'banking.cropInsurance': 'Crop Insurance',
    'banking.savingsAccount': 'Savings Account',
    'banking.currentAccount': 'Current Account',
    'banking.creditCard': 'Credit Card',
    'banking.digitalBanking': 'Digital Banking',
    'banking.mobileBanking': 'Mobile Banking',
    'banking.onlineBanking': 'Online Banking',
    'banking.atmServices': 'ATM Services',
    'banking.chequeBook': 'Cheque Book',
    'banking.demandDraft': 'Demand Draft',
    'banking.moneyTransfer': 'Money Transfer',
    'banking.fixedDeposit': 'Fixed Deposit',
    'banking.recurringDeposit': 'Recurring Deposit',
    'banking.termLoan': 'Term Loan',
    'banking.workingCapital': 'Working Capital',
    'banking.equipmentLoan': 'Equipment Loan',
    'banking.dairyLoan': 'Dairy Loan',
    'banking.poultryLoan': 'Poultry Loan',
    'banking.fisheriesLoan': 'Fisheries Loan',
    'banking.horticultureLoan': 'Horticulture Loan',
    'banking.organicFarmingLoan': 'Organic Farming Loan',
    'banking.greenhouseLoan': 'Greenhouse Loan',
    'banking.irrigationLoan': 'Irrigation Loan',
    'banking.landPurchaseLoan': 'Land Purchase Loan',
    'banking.farmhouseLoan': 'Farmhouse Loan',
    'banking.agriBusinessLoan': 'Agri Business Loan',
    'banking.ruralHousingLoan': 'Rural Housing Loan',
    'banking.twoWheelerLoan': 'Two Wheeler Loan',
    'banking.fourWheelerLoan': 'Four Wheeler Loan',
    'banking.personalLoan': 'Personal Loan',
    'banking.homeLoan': 'Home Loan',
    'banking.educationLoan': 'Education Loan',
    'banking.goldLoan': 'Gold Loan',
    'banking.vehicleLoan': 'Vehicle Loan',
    'banking.constructionLoan': 'Construction Loan',
    'banking.renovationLoan': 'Renovation Loan',
    'banking.medicalLoan': 'Medical Loan',
    'banking.weddingLoan': 'Wedding Loan',
    'banking.travelLoan': 'Travel Loan',
    'banking.consumerLoan': 'Consumer Loan',
    'banking.businessLoan': 'Business Loan',
    'banking.msmeLoan': 'MSME Loan',
    'banking.womenEntrepreneurLoan': 'Women Entrepreneur Loan',
    'banking.startupLoan': 'Startup Loan',
    'banking.exportLoan': 'Export Loan',
    'banking.importLoan': 'Import Loan',
    'banking.workingCapitalLoan': 'Working Capital Loan',
    'banking.termLoan': 'Term Loan',
    'banking.cashCredit': 'Cash Credit',
    'banking.overdraft': 'Overdraft',
    'banking.billDiscounting': 'Bill Discounting',
    'banking.letterOfCredit': 'Letter of Credit',
    'banking.bankGuarantee': 'Bank Guarantee',
    'banking.performanceGuarantee': 'Performance Guarantee',
    'banking.financialGuarantee': 'Financial Guarantee',
    'banking.bidBond': 'Bid Bond',
    'banking.advancePaymentGuarantee': 'Advance Payment Guarantee',
    'banking.retentionMoneyGuarantee': 'Retention Money Guarantee',
    'banking.warrantyGuarantee': 'Warranty Guarantee',
    'banking.maintenanceGuarantee': 'Maintenance Guarantee',
    'banking.supplyGuarantee': 'Supply Guarantee',
    'banking.performanceBond': 'Performance Bond',
    'banking.advancePaymentBond': 'Advance Payment Bond',
    'banking.bidBond': 'Bid Bond',
    'banking.retentionMoneyBond': 'Retention Money Bond',
    'banking.warrantyBond': 'Warranty Bond',
    'banking.maintenanceBond': 'Maintenance Bond',
    'banking.supplyBond': 'Supply Bond',
    'banking.performanceBond': 'Performance Bond',
    'banking.advancePaymentBond': 'Advance Payment Bond',
    'banking.bidBond': 'Bid Bond',
    'banking.retentionMoneyBond': 'Retention Money Bond',
    'banking.warrantyBond': 'Warranty Bond',
    'banking.maintenanceBond': 'Maintenance Bond',
    'banking.supplyBond': 'Supply Bond',
    'banking.city': 'City',
    'banking.district': 'District',
    'banking.coordinates': 'Coordinates',
    'banking.tryAgain': 'Try Again',
    'banking.detectingLocation': 'Detecting your location...',
    'banking.email': 'Email',
    'banking.visitWebsite': 'Visit Website',
    'banking.interestRateLabel': 'Interest Rate:',
    'banking.maxAmountLabel': 'Max Amount:',
    'banking.tenureLabel': 'Tenure:',
    'banking.note': 'Note:',
    'banking.interestRatesNote': 'Interest rates and terms are subject to change. Please contact the respective banks for the most current information.',
    'banking.governmentBenefits': 'Government Benefits:',
    'banking.governmentBenefitsNote': 'Many loans are eligible for government subsidies. Check with your local agricultural office for current programs.',
    
    // Bank names
    'banking.banks.tnGramaBank': 'Tamil Nadu Grama Bank',
    'banking.banks.bankOfBaroda': 'Bank of Baroda',
    'banking.banks.hdfcBank': 'HDFC Bank',
    'banking.banks.paccs': 'Primary Agricultural Cooperative Credit Societies (PACCS)',
    
    // Lending
    'lending.title': 'Micro Lending',
    'lending.subtitle': 'Community-based lending circles for Tamil Nadu farmers',
    'lending.home': 'Home',
    'lending.circles': 'Lending Circles',
    'lending.myLoans': 'My Loans',
    'lending.admin': 'Admin',
    'lending.welcomeTitle': 'Welcome to AgroConnect Micro Lending',
    'lending.welcomeSubtitle': 'Join trusted lending circles with fellow farmers across Tamil Nadu',
    'lending.joinCircle': 'Join a Circle',
    'lending.applyLoan': 'Apply for Loan',
    'lending.viewLoans': 'View My Loans',
    'lending.circlesAvailable': 'Lending Circles Available',
    'lending.membersOnline': 'Members Online',
    'lending.totalLoans': 'Total Loans',
    'lending.avgApprovalTime': 'Avg Approval Time',
    'lending.hours': 'hours',
    'lending.exploreCircles': 'Explore Circles',
    'lending.activeStatus': 'Active',
    'lending.fullStatus': 'Full',
    'lending.newStatus': 'New',
    'lending.members': 'Members',
    'lending.interestRate': 'Interest Rate',
    'lending.loanRange': 'Loan Range',
    'lending.completedLoans': 'Completed Loans',
    'lending.trustScore': 'Trust Score',
    'lending.memberContribution': 'Member Contribution',
    'lending.admin': 'Admin',
    'lending.joinWhatsApp': 'Join WhatsApp Group',
    'lending.alreadyJoined': 'Already Joined',
    'lending.requestLoan': 'Request Loan',
    'lending.pendingLoans': 'Pending Loans',
    'lending.approvedLoans': 'Approved Loans',
    'lending.repaidLoans': 'Repaid Loans',
    'lending.amount': 'Amount',
    'lending.purpose': 'Purpose',
    'lending.status': 'Status',
    'lending.dueDate': 'Due Date',
    'lending.monthlyEMI': 'Monthly EMI',
    'lending.appliedDate': 'Applied Date',
    'lending.repaidDate': 'Repaid Date',
    'lending.pending': 'Pending',
    'lending.approved': 'Approved',
    'lending.repaid': 'Repaid',
    'lending.loanRequests': 'Loan Requests',
    'lending.approveRequest': 'Approve Request',
    'lending.rejectRequest': 'Reject Request',
    'lending.requestedBy': 'Requested by',
    'lending.requestedOn': 'Requested on',
    'lending.repaymentDuration': 'Repayment Duration',
    'lending.applyForLoan': 'Apply for Loan',
    'lending.selectCircle': 'Select Lending Circle',
    'lending.chooseCircle': 'Choose a lending circle',
    'lending.loanAmount': 'Loan Amount',
    'lending.enterAmount': 'Enter amount needed',
    'lending.describePurpose': 'Describe how you plan to use the loan',
    'lending.selectDuration': 'Select duration',
    'lending.months': 'months',
    'lending.submitApplication': 'Submit Application',
    'lending.cancel': 'Cancel',
    'lending.successfullyJoined': 'Successfully joined the circle! WhatsApp group opened.',
    'lending.applicationSubmitted': 'Loan application submitted successfully!',
    'lending.close': 'Close',
    'lending.joinCircleDesc': 'Connect with farmers in your community',
    'lending.requestLoanDesc': 'Get quick access to affordable financing',
    'lending.buildTrust': 'Build Trust',
    'lending.buildTrustDesc': 'Grow your community through responsible lending',
    'lending.activeCircles': 'Active Circles',
    'lending.totalMembers': 'Total Members',
    'lending.loansCompleted': 'Loans Completed',
    'lending.totalLending': 'Total Lending',
    'lending.availableCircles': 'Available Circles',
    'lending.editProfile': 'Edit Profile',
    'lending.welcome': 'Welcome,',
    'lending.members': 'Members',
    'lending.interestRate': 'Interest Rate',
    'lending.loanRange': 'Loan Range',
    'lending.completedLoans': 'Completed Loans',
    'lending.trustScore': 'Trust Score',
    'lending.memberContribution': 'Member Contribution',
    'lending.admin': 'Admin',
    'lending.joinWhatsApp': 'Join WhatsApp Group',
    'lending.alreadyJoined': 'Already Joined',
    'lending.circleFull': 'Circle Full',
    'lending.joinedWhatsApp': 'Joined WhatsApp Group',
    'lending.myLoans': 'My Loans',
    'lending.requestLoan': 'Request Loan',
    'lending.selectCircle': 'Select Circle',
    'lending.chooseCircle': 'Choose a lending circle',
    'lending.loanAmount': 'Loan Amount (₹)',
    'lending.enterAmount': 'Enter amount needed',
    'lending.describePurpose': 'Describe how you plan to use the loan',
    'lending.selectDuration': 'Select duration',
    'lending.submitApplication': 'Submit Application',
    'lending.cancel': 'Cancel',
    'lending.appliedOn': 'Applied on',
    'lending.repaidOn': 'Repaid on',
    'lending.dueDate': 'Due Date',
    'lending.monthlyEMI': 'Monthly EMI',
    'lending.adminPanel': 'Admin Panel',
    'lending.pendingLoanRequests': 'Pending Loan Requests',
    'lending.from': 'From',
    'lending.purpose': 'Purpose',
    'lending.duration': 'Duration',
    'lending.requestedOn': 'Requested on',
    'lending.approve': 'Approve',
    'lending.reject': 'Reject',
    'lending.noPendingRequests': 'No pending loan requests',
    'lending.checkBackLater': 'Check back later for new requests',
    'lending.howMicroLendingWorks': 'How Micro-Lending Works',
    'lending.joinCircle': 'Join Circle',
    'lending.connectWithFarmers': 'Connect with farmers in your community',
    'lending.contribute': 'Contribute',
    'lending.makeContribution': 'Make a one-time contribution to the circle\'s lending pool',
    'lending.requestLoan': 'Request Loan',
    'lending.applyForLoans': 'Apply for loans when needed, with circle member approval',
    'lending.repayAndGrow': 'Repay & Grow',
    'lending.repayOnTime': 'Repay on time to build trust and grow the community fund',
    'lending.editProfile': 'Edit Profile',
    'lending.yourName': 'Your Name',
    'lending.enterYourName': 'Enter your name',
    'lending.saveChanges': 'Save Changes',
    'lending.whatsAppMessageSent': 'WhatsApp Message Sent!',
    'lending.loanRequestSent': 'Your loan request has been sent to the admin via WhatsApp',
    'lending.whatsAppGroupOpened': 'WhatsApp Group Opened!',
    'lending.joinGroupForLoanRequests': 'Join the group to access loan requests',
    
    // Equipment
    'equipment.title': 'Farming Equipment',
    'equipment.subtitle': 'Rent modern equipment for your farm',
    'equipment.rentNow': 'Rent Now',
    'equipment.addToCart': 'Add to Cart',
    'equipment.pricePerDay': 'per day',
    
    // Forum
    'forum.title': 'Community Forum',
    'forum.subtitle': 'Share knowledge and connect with farmers',
    'forum.createPost': 'Create Post',
    'forum.search': 'Search posts...',
    'forum.categories': 'Categories',
    'forum.recent': 'Recent',
    'forum.popular': 'Popular',
    'forum.like': 'Like',
    'forum.reply': 'Reply',
    'forum.share': 'Share',
    
    // Lending
    'lending.title': 'Micro Lending',
    'lending.subtitle': 'Community-based lending for farmers',
    'lending.joinCircle': 'Join Circle',
    'lending.requestLoan': 'Request Loan',
    'lending.myLoans': 'My Loans',
    'lending.admin': 'Admin Panel',
    
    // Expenses
    'expenses.title': 'Expense Tracker',
    'expenses.subtitle': 'Track your farming expenses',
    'expenses.addExpense': 'Add Expense',
    'expenses.category': 'Category',
    'expenses.amount': 'Amount',
    'expenses.description': 'Description',
    'expenses.date': 'Date',
    'expenses.recentExpenses': 'Recent Expenses',
    'expenses.totalExpenses': 'Total Expenses',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.note': 'Note',
    'common.available': 'Available',
    
    // Schemes page
    'schemes.title': 'Government Schemes',
    'schemes.subtitle': 'Access Tamil Nadu agricultural schemes and benefits',
    'schemes.searchPlaceholder': 'Search schemes...',
    'schemes.filterAll': 'All Schemes',
    'schemes.filterActive': 'Active',
    'schemes.filterUpcoming': 'Upcoming',
    'schemes.filterExpired': 'Expired',
    'schemes.applyNow': 'Apply Now',
    'schemes.viewDetails': 'View Details',
    'schemes.eligibility': 'Eligibility',
    'schemes.benefits': 'Benefits',
    'schemes.deadline': 'Application Deadline',
    'schemes.status': 'Status',
    'schemes.amount': 'Amount',
    'schemes.category': 'Category',
    'schemes.agricultural': 'Agricultural',
    'schemes.livestock': 'Livestock',
    'schemes.irrigation': 'Irrigation',
    'schemes.equipment': 'Equipment',
    'schemes.insurance': 'Insurance',
    'schemes.loan': 'Loan',
    'schemes.subsidy': 'Subsidy',
    'schemes.training': 'Training',
    'schemes.other': 'Other',
    
    // Forum page
    'forum.title': 'Community Forum',
    'forum.subtitle': 'Connect with fellow farmers and share knowledge',
    'forum.createPost': 'Create Post',
    'forum.searchPlaceholder': 'Search posts...',
    'forum.categories': 'Categories',
    'forum.allPosts': 'All Posts',
    'forum.myPosts': 'My Posts',
    'forum.popular': 'Popular',
    'forum.recent': 'Recent',
    'forum.trending': 'Trending',
    'forum.like': 'Like',
    'forum.reply': 'Reply',
    'forum.share': 'Share',
    'forum.report': 'Report',
    'forum.edit': 'Edit',
    'forum.delete': 'Delete',
    'forum.postTitle': 'Post Title',
    'forum.postContent': 'Write your post...',
    'forum.selectCategory': 'Select Category',
    'forum.addImage': 'Add Image',
    'forum.publish': 'Publish',
    'forum.cancel': 'Cancel',
    'forum.replies': 'Replies',
    'forum.views': 'Views',
    'forum.postedBy': 'Posted by',
    'forum.ago': 'ago',
    'forum.hours': 'hours',
    'forum.days': 'days',
    'forum.weeks': 'weeks',
    'forum.months': 'months',
    'forum.years': 'years',
    'forum.writeReply': 'Write a reply...',
    'forum.submitReply': 'Submit Reply',
    'forum.noPosts': 'No posts found',
    'forum.loadMore': 'Load More',
    
    // Banking page
    'banking.title': 'Banking Services',
    'banking.subtitle': 'Agricultural loans, insurance, and financial services',
    'banking.loans': 'Loans',
    'banking.insurance': 'Insurance',
    'banking.savings': 'Savings',
    'banking.investments': 'Investments',
    'banking.applyLoan': 'Apply for Loan',
    'banking.getInsurance': 'Get Insurance',
    'banking.openAccount': 'Open Account',
    'banking.interestRate': 'Interest Rate',
    'banking.tenure': 'Tenure',
    'banking.maxAmount': 'Maximum Amount',
    'banking.processingFee': 'Processing Fee',
    'banking.eligibility': 'Eligibility',
    'banking.documents': 'Required Documents',
    'banking.applyNow': 'Apply Now',
    'banking.learnMore': 'Learn More',
    'banking.agriculturalLoan': 'Agricultural Loan',
    'banking.equipmentLoan': 'Equipment Loan',
    'banking.cropInsurance': 'Crop Insurance',
    'banking.livestockInsurance': 'Livestock Insurance',
    'banking.savingsAccount': 'Savings Account',
    'banking.currentAccount': 'Current Account',
    'banking.fixedDeposit': 'Fixed Deposit',
    'banking.recurringDeposit': 'Recurring Deposit',
  },
  ta: {
    // Navigation
    'nav.dashboard': 'முகப்பு',
    'nav.equipment': 'கருவிகள்',
    'nav.orders': 'ஆர்டர்கள்',
    'nav.forum': 'மன்றம்',
    'nav.lending': 'கடன்',
    'nav.expenses': 'செலவுகள்',
    'nav.insights': 'நுண்ணறிவு',
    'nav.schemes': 'திட்டங்கள்',
    'nav.banking': 'வங்கி',
    'nav.location': 'இடம்',
    
    // Header
    'header.cart': 'கார்ட்',
    'header.signIn': 'உள்நுழைய',
    'header.signUp': 'பதிவு செய்',
    'header.language': 'மொழி',
    
    // Dashboard
    'dashboard.title': 'AgroConnect-க்கு வரவேற்கிறோம்',
    'dashboard.subtitle': 'தமிழ்நாடு விவசாயிகளை வலுப்படுத்துதல்',
    'dashboard.equipment.title': 'நவீன கருவிகள்',
    'dashboard.equipment.subtitle': 'உயர்தர விவசாய கருவிகளை வாடகைக்கு எடுங்கள்',
    'dashboard.lending.title': 'சிறு கடன்',
    'dashboard.lending.subtitle': 'சமூக அடிப்படையிலான கடன் வட்டங்கள்',
    'dashboard.forum.title': 'சமூக மன்றம்',
    'dashboard.forum.subtitle': 'விவசாயிகளுடன் இணைந்து கொள்ளுங்கள்',
    'dashboard.expenses.title': 'செலவு கண்காணிப்பு',
    'dashboard.expenses.subtitle': 'உங்கள் விவசாய செலவுகளை கண்காணியுங்கள்',
    'dashboard.insights.title': 'AI நுண்ணறிவு',
    'dashboard.insights.subtitle': 'ஸ்மார்ட் விவசாய பரிந்துரைகள்',
    'dashboard.schemes.title': 'அரசு திட்டங்கள்',
    'dashboard.schemes.subtitle': 'தமிழ்நாடு திட்டங்களை அணுகுங்கள்',
    'dashboard.banking.title': 'வங்கி சேவைகள்',
    'dashboard.banking.subtitle': 'விவசாய கடன்கள் மற்றும் காப்பீடு',
    'dashboard.stats.totalExpenses': 'மொத்த செலவுகள்',
    'dashboard.stats.activeLoans': 'செயலில் உள்ள கடன்கள்',
    'dashboard.stats.equipmentBookings': 'கருவி முன்பதிவுகள்',
    'dashboard.stats.forumPosts': 'மன்ற இடுகைகள்',
    'dashboard.stats.expensesTrend': 'கடந்த மாதத்திலிருந்து 12%',
    'dashboard.stats.loansTrend': 'இந்த வாரம் 2 அனுமதிக்கப்பட்டது',
    'dashboard.stats.equipmentTrend': 'அடுத்து: நாளை காலை 9 மணி',
    'dashboard.stats.forumTrend': 'இந்த வாரம் 5 புதியவை',
    'dashboard.actions.bookEquipment': 'கருவி முன்பதிவு',
    'dashboard.actions.bookEquipmentDesc': 'டிராக்டர்கள், அறுவடை இயந்திரங்கள் மற்றும் பலவற்றை முன்பதிவு செய்யுங்கள்',
    'dashboard.actions.joinForum': 'மன்றத்தில் சேருங்கள்',
    'dashboard.actions.joinForumDesc': 'விவசாயிகளுடன் இணைந்து கொள்ளுங்கள்',
    'dashboard.actions.trackExpenses': 'செலவுகளை கண்காணியுங்கள்',
    'dashboard.actions.trackExpensesDesc': 'உங்கள் விவசாய செலவுகளை கண்காணியுங்கள்',
    'dashboard.actions.viewSchemes': 'திட்டங்களை பார்க்கவும்',
    'dashboard.actions.viewSchemesDesc': 'அரசு திட்டங்களை அணுகுங்கள்',
    
    // Dashboard additional content
    'dashboard.stats.title': 'விரைவு புள்ளிவிவரங்கள்',
    'dashboard.quickActions.title': 'விரைவு செயல்கள்',
    'dashboard.recentActivity.title': 'சமீபத்திய செயல்பாடு',
    'dashboard.getStarted': 'தொடங்குங்கள்',
    'dashboard.premium': 'பிரீமியம்',
    'dashboard.instant': 'உடனடி',
    'dashboard.organic': 'இயற்கை',
    'dashboard.smart': 'ஸ்மார்ட்',
    'dashboard.active': 'செயலில்',
    'dashboard.secure': 'பாதுகாப்பான',
    'dashboard.fromPrice': '₹2,500/நாள் முதல்',
    'dashboard.upToPrice': '₹50,000 வரை',
    'dashboard.upToOff': '30% வரை தள்ளுபடி',
    'dashboard.liveData': 'நேரடி தரவு',
    'dashboard.members': '15,000+ உறுப்பினர்கள்',
    'dashboard.insurancePrice': '₹500/ஆண்டு முதல்',
    
    // Recent activity
    'dashboard.activity.tractorBooked': 'நாளைக்கு டிராக்டர் முன்பதிவு செய்யப்பட்டது',
    'dashboard.activity.loanApproved': 'கடன் அனுமதிக்கப்பட்டது - ₹15,000',
    'dashboard.activity.forumReply': 'பூச்சி கட்டுப்பாட்டில் புதிய மன்ற பதில்',
    'dashboard.activity.fertilizerOrder': 'உர ஆர்டர் முடிந்தது',
    'dashboard.activity.hoursAgo': 'மணி நேரங்களுக்கு முன்',
    'dashboard.activity.dayAgo': 'நாளுக்கு முன்',
    'dashboard.activity.daysAgo': 'நாட்களுக்கு முன்',
    
    // Schemes
    'schemes.title': 'அரசு திட்டங்கள்',
    'schemes.subtitle': 'தமிழ்நாடு விவசாயி திட்டங்கள் மற்றும் நன்மைகள்',
    'schemes.search': 'திட்டங்களை தேடுங்கள்...',
    'schemes.filterByCategory': 'வகையால் வடிகட்டு',
    'schemes.filterByCaste': 'சாதியால் வடிகட்டு',
    'schemes.allCategories': 'அனைத்து வகைகள்',
    'schemes.allCastes': 'அனைத்து சாதிகள்',
    'schemes.viewDetails': 'விவரங்களை பார்க்கவும்',
    'schemes.applyNow': 'இப்போது விண்ணப்பிக்கவும்',
    'schemes.benefits': 'நன்மைகள்',
    'schemes.eligibility': 'தகுதி',
    'schemes.applicationProcess': 'விண்ணப்ப செயல்முறை',
    'schemes.contact': 'தொடர்பு',
    'schemes.directBenefits': 'நேரடி நன்மைகள்',
    'schemes.categories.general': 'பொது',
    'schemes.categories.financial': 'நிதி',
    'schemes.categories.agricultural': 'விவசாய',
    'schemes.categories.insurance': 'காப்பீடு',
    'schemes.categories.education': 'கல்வி',
    'schemes.categories.healthcare': 'சுகாதாரம்',
    'schemes.categories.women': 'பெண்கள்',
    'schemes.categories.youth': 'இளைஞர்கள்',
    'schemes.categories.senior': 'முதியவர்கள்',
    'schemes.categories.disabled': 'மாற்றுத்திறனாளிகள்',
    'schemes.categories.welfare': 'நலன்புரி',
    'schemes.categories.development': 'வளர்ச்சி',
    'schemes.categories.irrigation': 'பாசனம்',
    'schemes.categories.equipment': 'கருவிகள்',
    'schemes.categories.infrastructure': 'அடிப்படை வசதிகள்',
    'schemes.categories.training': 'பயிற்சி',
    'schemes.categories.utility': 'பயன்பாடு',
    'schemes.categories.tribal': 'பழங்குடி',
    'schemes.castes.sc': 'பட்டியல் சாதி',
    'schemes.castes.st': 'பட்டியல் பழங்குடி',
    'schemes.castes.obc': 'பிற்படுத்தப்பட்ட வகுப்பு',
    'schemes.castes.mbc': 'மிகவும் பிற்படுத்தப்பட்ட வகுப்பு',
    'schemes.castes.general': 'பொது',
    'schemes.castes.minority': 'சிறுபான்மை',
    'schemes.selectCommunity': 'உங்கள் சமூகத்தை தேர்ந்தெடுக்கவும்',
    'schemes.selectCommunityDesc': 'அனைத்து விவசாயிகளுக்கும் கிடைக்கும் பொது திட்டங்களுடன் தனிப்பயனாக்கப்பட்ட திட்டங்களை பார்க்க உங்கள் சமூகத்தை தேர்ந்தெடுக்கவும்',
    'schemes.generalSchemesNote': 'குறிப்பு: சமூகத்தை தேர்ந்தெடுக்காமலேயே கீழே அனைத்து விவசாயிகளுக்கும் கிடைக்கும் பொது திட்டங்களை உலாவலாம்.',
    'schemes.changeCommunity': 'சமூகத்தை மாற்றவும்',
    'schemes.noSchemesFound': 'திட்டங்கள் எதுவும் கிடைக்கவில்லை',
    'schemes.noSchemesFoundDesc': 'உங்கள் தேடல் வார்த்தைகள் அல்லது வகை வடிகட்டியை சரிசெய்ய முயற்சிக்கவும்',
    'schemes.howToApply': 'தமிழ்நாடு விவசாயி திட்டங்களுக்கு விண்ணப்பிக்கும் முறை',
    'schemes.howToApplyDesc': 'தமிழ்நாடு விவசாயி திட்டங்களை கண்டறிந்து விண்ணப்பிக்க இந்த எளிய படிகளை பின்பற்றுங்கள்',
    'schemes.step1.title': 'திட்டங்களை உலாவுங்கள்',
    'schemes.step1.desc1': 'மேலே உள்ள விருப்பங்களிலிருந்து உங்கள் சமூகத்தை தேர்ந்தெடுக்கவும்',
    'schemes.step1.desc2': 'குறிப்பிட்ட திட்டங்களை கண்டறிய தேடல் பட்டியை பயன்படுத்தவும்',
    'schemes.step1.desc3': 'வகையால் வடிகட்டவும் (விவசாயம், காப்பீடு, முதலியன)',
    'schemes.step1.desc4': 'திட்ட விவரங்கள் மற்றும் நன்மைகளை படிக்கவும்',
    'schemes.step2.title': 'தேவைகளை சரிபார்க்கவும்',
    'schemes.step2.desc1': 'ஒவ்வொரு திட்டத்திற்கும் தகுதி அளவுகோல்களை மறுஆய்வு செய்யவும்',
    'schemes.step2.desc2': 'தேவையான ஆவணங்கள் உங்களிடம் உள்ளதா என்பதை உறுதிப்படுத்தவும்',
    'schemes.step2.desc3': 'நில பதிவுகள் மற்றும் சான்றிதழ்களை சரிபார்க்கவும்',
    'schemes.step2.desc4': 'வயது மற்றும் சமூக தேவைகளை சரிபார்க்கவும்',
    'schemes.step3.title': 'ஆன்லைனில் விண்ணப்பிக்கவும்',
    'schemes.step3.desc1': 'தமிழ்நாடு e-சேவை போர்ட்டலை பார்வையிடவும்',
    'schemes.step3.desc2': 'உங்கள் விவசாயி கணக்கை உருவாக்கவும்',
    'schemes.step3.desc3': 'தேவையான விவரங்களுடன் விண்ணப்ப படிவங்களை நிரப்பவும்',
    'schemes.step3.desc4': 'தேவையான ஆவணங்களை பதிவேற்றவும்',
    'schemes.step4.title': 'விண்ணப்பத்தை கண்காணிக்கவும்',
    'schemes.step4.desc1': 'விண்ணப்ப நிலையை ஆன்லைனில் சரிபார்க்கவும்',
    'schemes.step4.desc2': 'உங்கள் மொபைலில் SMS புதுப்பிப்புகளை பெறவும்',
    'schemes.step4.desc3': 'தேவைப்பட்டால் அருகிலுள்ள e-சேவை மையத்தை பார்வையிடவும்',
    'schemes.step4.desc4': 'துறை அதிகாரிகளுடன் தொடர்ந்து பின்தொடரவும்',
    'schemes.quickLinks': 'விரைவு இணைப்புகள்',
    'schemes.eSevaiPortal': 'தமிழ்நாடு e-சேவை போர்ட்டல்',
    'schemes.helpline': 'உதவி வரி: 1800-425-1556',
    'schemes.agricultureDepartment': 'விவசாய துறை',
    'schemes.howToApplyTractor': 'இலவச டிராக்டருக்கு விண்ணப்பிக்கும் முறை',
    'schemes.top5Schemes': 'விவசாயிகளுக்கான முதல் 5 திட்டங்கள்',
    'schemes.note': 'குறிப்பு:',
    'schemes.noteText': 'அனைத்து திட்டங்களும் அரசு வழிகாட்டுதல்கள் மற்றும் தகுதி அளவுகோல்களுக்கு உட்பட்டவை.',
    'schemes.verifyInfo': 'தற்போதைய தகவலுக்கு அதிகாரப்பூர்வ தமிழ்நாடு அரசு ஆதாரங்களிலிருந்து சரிபார்க்கவும்.',
    
    // Scheme titles
    'schemes.cmFarmersProtection.title': 'முதலமைச்சர் விவசாயிகள் பாதுகாப்பு திட்டம்',
    'schemes.summerPloughing.title': 'கோடை உழவு ஊக்கத்தொகை',
    'schemes.wellRenovation.title': 'கிணறு புதுப்பிப்பு மானியம் (சோதனை)',
    'schemes.naturalFarming.title': 'இயற்கை விவசாய திட்டம்',
    'schemes.hillFarmers.title': 'மலை விவசாயிகள் வளர்ச்சி திட்டம்',
    'schemes.sugarcanePrice.title': 'கரும்பு விலை ஊக்கத்தொகை',
    'schemes.cropInsurance.title': 'பயிர் காப்பீடு மானியம்',
    'schemes.paddyProcurement.title': 'நெல் கொள்முதல் MSP + ஊக்கத்தொகை',
    'schemes.agriMachinery.title': 'விவசாய இயந்திர மானியம்',
    'schemes.cmServiceCentres.title': 'முதலமைச்சர் விவசாயிகள் சேவை மையங்கள்',
    'schemes.nutritionFarming.title': 'ஊட்டச்சத்து விவசாய பணி',
    'schemes.internationalExposure.title': 'சர்வதேச அனுபவ பயணங்கள்',
    'schemes.electricitySubsidy.title': 'மின்சார மானியம்',
    'schemes.scDevelopment.title': 'பட்டியல் சாதி விவசாயிகள் வளர்ச்சி திட்டம்',
    'schemes.bcDevelopment.title': 'பிற்படுத்தப்பட்ட வகுப்பு வளர்ச்சி திட்டம்',
    'schemes.mbcAgriculture.title': 'மிகவும் பிற்படுத்தப்பட்ட வகுப்பு விவசாய திட்டம்',
    'schemes.minorityFarmers.title': 'சிறுபான்மை விவசாயிகள் வளர்ச்சி திட்டம்',
    'schemes.tribalFarmers.title': 'பழங்குடி விவசாயிகள் நலன்புரி திட்டம்',
    'schemes.womenFarmers.title': 'பெண் விவசாயிகள் அதிகாரமளிப்பு திட்டம்',
    'schemes.youthFarmers.title': 'இளைஞர் விவசாயிகள் ஸ்டார்ட்அப் திட்டம்',
    
    // Scheme descriptions
    'schemes.cmFarmersProtection.desc': 'இயற்கை பேரழிவுகள் மற்றும் பயிர் தோல்விகளுக்கு எதிராக விவசாயிகளுக்கு விரிவான காப்பீட்டு பாதுகாப்பு.',
    'schemes.summerPloughing.desc': 'மண் ஆரோக்கியம் மற்றும் நீர் தக்கவைப்பை மேம்படுத்த கோடை உழவுக்கு நேரடி நிதி ஊக்கத்தொகை.',
    'schemes.wellRenovation.desc': 'நீர் கிடைப்பை மேம்படுத்த கைவிடப்பட்ட கிணறுகளை புதுப்பிப்பதற்கு நிதி ஆதரவு.',
    'schemes.naturalFarming.desc': 'இயற்கை விவசாய முறைகளுக்கு மாற விவசாயிகளுக்கு ஆதரவு.',
    'schemes.hillFarmers.desc': 'மலைப்பகுதிகளில் உள்ள விவசாயிகளுக்கான சிறப்பு வளர்ச்சி திட்டங்கள்.',
    'schemes.sugarcanePrice.desc': 'FRP-க்கு மேல் கரும்பு விவசாயிகளுக்கு நேரடி விலை ஊக்கத்தொகை.',
    'schemes.cropInsurance.desc': 'அனைத்து விவசாயிகளுக்கும் பயிர் காப்பீட்டு பிரீமியம் முழுமையாக மானியம்.',
    'schemes.paddyProcurement.desc': 'அரசு கொள்முதல் விலைக்கு மேல் நெல் விவசாயிகளுக்கு மாநில ஊக்கத்தொகை.',
    'schemes.agriMachinery.desc': 'விவசாய இயந்திரங்களுக்கு 60% மானியம் மற்றும் நிறுவல் உதவி.',
    'schemes.cmServiceCentres.desc': 'விவசாயிகளுக்கான சேவை மையங்கள் அமைப்பதற்கு முதலமைச்சர் திட்டம்.',
    'schemes.nutritionFarming.desc': 'ஊட்டச்சத்து மிக்க பயிர்களை வளர்ப்பதற்கு இலவச விதைகள் மற்றும் மரக்கன்றுகள்.',
    'schemes.internationalExposure.desc': 'முன்னேறிய விவசாயிகளுக்கு சர்வதேச விவசாய நுட்பங்களை கற்க முழுமையாக நிதியளிக்கப்பட்ட பயணங்கள்.',
    'schemes.electricitySubsidy.desc': 'விவசாய நோக்கங்களுக்கான மின்சாரத்திற்கு மானியம்.',
    'schemes.scDevelopment.desc': 'பட்டியல் சாதி விவசாயிகளுக்கான விரிவான வளர்ச்சி திட்டங்கள்.',
    'schemes.bcDevelopment.desc': 'பிற்படுத்தப்பட்ட வகுப்பு விவசாயிகளுக்கான நவீன விவசாய நடைமுறைகளில் கவனம் செலுத்தும் வளர்ச்சி திட்டங்கள்.',
    'schemes.mbcAgriculture.desc': 'மிகவும் பிற்படுத்தப்பட்ட வகுப்பு விவசாயிகளுக்கான சிறப்பு விவசாய வளர்ச்சி திட்டங்கள்.',
    'schemes.minorityFarmers.desc': 'நிதி உதவி மற்றும் பயிற்சி உட்பட சிறுபான்மை சமூக விவசாயிகளுக்கான வளர்ச்சி திட்டங்கள்.',
    'schemes.tribalFarmers.desc': 'பழங்குடி பகுதிகளில் உள்ள பட்டியல் பழங்குடி விவசாயிகளுக்கான விரிவான நலன்புரி திட்டங்கள்.',
    'schemes.womenFarmers.desc': 'அதிகாரமளிப்பு மற்றும் நிதி சுதந்திரத்தில் கவனம் செலுத்தும் பெண் விவசாயிகளுக்கான சிறப்பு திட்டங்கள்.',
    'schemes.youthFarmers.desc': 'நவீன தொழில்நுட்பத்துடன் விவசாய நடவடிக்கைகளைத் தொடங்க இளைஞர் விவசாயிகளுக்கு ஆதரவு.',
    
    // Common scheme text
    'schemes.allFarmers': 'அனைத்து விவசாயிகள்',
    'schemes.farmersWithLand': 'நில பதிவுகள் உள்ள விவசாயிகள்',
    'schemes.registeredFarmers': 'விவசாய துறையில் பதிவு செய்யப்பட்ட விவசாயிகள்',
    'schemes.onlineApplication': 'தமிழ்நாடு e-சேவை போர்ட்டல் மூலம் ஆன்லைன் விண்ணப்பம்',
    'schemes.agricultureDepartment': 'விவசாய துறை',
    'schemes.waterResources': 'நீர் வள துறை',
    'schemes.hillDevelopment': 'மலை பகுதி வளர்ச்சி நிறுவனம்',
    'schemes.sugarMills': 'சர்க்கரை ஆலைகள்',
    'schemes.procurementCenters': 'கொள்முதல் மையங்கள்',
    'schemes.agricultureEngineering': 'விவசாய பொறியியல் துறை',
    'schemes.startupMission': 'ஸ்டார்ட்அப் பணி',
    'schemes.womenDevelopment': 'பெண்கள் வளர்ச்சி நிறுவனம்',
    'schemes.tribalWelfare': 'பழங்குடி நலன்புரி துறை',
    'schemes.minoritiesCorporation': 'சிறுபான்மை சமூக பொருளாதார வளர்ச்சி நிறுவனம்',
    'schemes.mbcCorporation': 'MBC நிறுவனம்',
    'schemes.bcWelfare': 'பிற்படுத்தப்பட்ட வகுப்பு நலன்புரி துறை',
    'schemes.adiDravidarWelfare': 'அடி திராவிடர் நலன்புரி அலுவலகம்',
    
    // Banking
    'banking.title': 'தமிழ்நாடு விவசாயி வங்கி போர்ட்டல்',
    'banking.subtitle': 'தமிழ்நாடு முழுவதும் விவசாயிகளுக்கான விரிவான வங்கி தீர்வுகள்',
    'banking.searchBanks': 'வங்கிகளை தேடுங்கள்...',
    'banking.findNearbyBranches': 'அருகிலுள்ள கிளைகளை கண்டறியுங்கள்',
    'banking.getLocation': 'எனது இடத்தை பெறுங்கள்',
    'banking.locationError': 'இடத்தின் தகவல் கிடைக்கவில்லை',
    'banking.loadingLocation': 'உங்கள் இடத்தை பெறுகிறது...',
    'banking.bankDetails': 'வங்கி விவரங்கள்',
    'banking.loanSchemes': 'கடன் திட்டங்கள்',
    'banking.branches': 'கிளைகள்',
    'banking.contact': 'தொடர்பு',
    'banking.website': 'வலைத்தளம்',
    'banking.phone': 'தொலைபேசி',
    'banking.address': 'முகவரி',
    'banking.timings': 'நேரங்கள்',
    'banking.ifscCode': 'IFSC குறியீடு',
    'banking.interestRate': 'வட்டி விகிதம்',
    'banking.maxAmount': 'அதிகபட்ச தொகை',
    'banking.tenure': 'காலம்',
    'banking.eligibility': 'தகுதி',
    'banking.documents': 'தேவையான ஆவணங்கள்',
    'banking.specialFeatures': 'சிறப்பு அம்சங்கள்',
    'banking.eligibilityCriteria': 'தகுதி அளவுகோல்கள்',
    'banking.applyNow': 'இப்போது விண்ணப்பிக்கவும்',
    'banking.viewDetails': 'விவரங்களை பார்க்கவும்',
    'banking.nearbyBranches': 'அருகிலுள்ள கிளைகள்',
    'banking.noBranchesFound': 'உங்கள் பகுதியில் கிளைகள் எதுவும் கிடைக்கவில்லை',
    'banking.selectBank': 'விவரங்களை பார்க்க வங்கியை தேர்ந்தெடுக்கவும்',
    'banking.selectLoan': 'விவரங்களை பார்க்க கடன் திட்டத்தை தேர்ந்தெடுக்கவும்',
    'banking.agriculturalLoans': 'விவசாய கடன்கள்',
    'banking.cropInsurance': 'பயிர் காப்பீடு',
    'banking.savingsAccount': 'சேமிப்பு கணக்கு',
    'banking.currentAccount': 'நடப்பு கணக்கு',
    'banking.creditCard': 'கிரெடிட் கார்டு',
    'banking.digitalBanking': 'டிஜிட்டல் வங்கியியல்',
    'banking.mobileBanking': 'மொபைல் வங்கியியல்',
    'banking.onlineBanking': 'ஆன்லைன் வங்கியியல்',
    'banking.atmServices': 'ATM சேவைகள்',
    'banking.chequeBook': 'செக் புத்தகம்',
    'banking.demandDraft': 'டிமாண்ட் டிராஃப்ட்',
    'banking.moneyTransfer': 'பண பரிமாற்றம்',
    'banking.fixedDeposit': 'நிலையான வைப்பு',
    'banking.recurringDeposit': 'தொடர்ச்சியான வைப்பு',
    'banking.termLoan': 'கால கடன்',
    'banking.workingCapital': 'பணியாளர் மூலதனம்',
    'banking.equipmentLoan': 'கருவி கடன்',
    'banking.dairyLoan': 'பால் கடன்',
    'banking.poultryLoan': 'கோழி கடன்',
    'banking.fisheriesLoan': 'மீன்வளம் கடன்',
    'banking.horticultureLoan': 'தோட்டக்கலை கடன்',
    'banking.organicFarmingLoan': 'இயற்கை விவசாய கடன்',
    'banking.greenhouseLoan': 'கிரீன்ஹவுஸ் கடன்',
    'banking.irrigationLoan': 'பாசன கடன்',
    'banking.landPurchaseLoan': 'நில வாங்கும் கடன்',
    'banking.farmhouseLoan': 'பண்ணை வீடு கடன்',
    'banking.agriBusinessLoan': 'விவசாய வணிக கடன்',
    'banking.ruralHousingLoan': 'கிராமிய வீடு கடன்',
    'banking.twoWheelerLoan': 'இரண்டு சக்கர கடன்',
    'banking.fourWheelerLoan': 'நான்கு சக்கர கடன்',
    'banking.personalLoan': 'தனிப்பட்ட கடன்',
    'banking.homeLoan': 'வீடு கடன்',
    'banking.educationLoan': 'கல்வி கடன்',
    'banking.goldLoan': 'தங்க கடன்',
    'banking.vehicleLoan': 'வாகன கடன்',
    'banking.constructionLoan': 'கட்டுமான கடன்',
    'banking.renovationLoan': 'புதுப்பிப்பு கடன்',
    'banking.medicalLoan': 'மருத்துவ கடன்',
    'banking.weddingLoan': 'திருமண கடன்',
    'banking.travelLoan': 'பயண கடன்',
    'banking.consumerLoan': 'நுகர்வோர் கடன்',
    'banking.businessLoan': 'வணிக கடன்',
    'banking.msmeLoan': 'MSME கடன்',
    'banking.womenEntrepreneurLoan': 'பெண் தொழில்முனைவோர் கடன்',
    'banking.startupLoan': 'ஸ்டார்ட்அப் கடன்',
    'banking.exportLoan': 'ஏற்றுமதி கடன்',
    'banking.importLoan': 'இறக்குமதி கடன்',
    'banking.workingCapitalLoan': 'பணியாளர் மூலதன கடன்',
    'banking.cashCredit': 'பண கிரெடிட்',
    'banking.overdraft': 'ஓவர்டிராஃப்ட்',
    'banking.billDiscounting': 'பில் தள்ளுபடி',
    'banking.letterOfCredit': 'கிரெடிட் கடிதம்',
    'banking.bankGuarantee': 'வங்கி உத்தரவாதம்',
    'banking.performanceGuarantee': 'செயல்திறன் உத்தரவாதம்',
    'banking.financialGuarantee': 'நிதி உத்தரவாதம்',
    'banking.bidBond': 'ஏல பிணை',
    'banking.advancePaymentGuarantee': 'முன்பண உத்தரவாதம்',
    'banking.retentionMoneyGuarantee': 'தக்க வைப்பு பண உத்தரவாதம்',
    'banking.warrantyGuarantee': 'உத்தரவாத உத்தரவாதம்',
    'banking.maintenanceGuarantee': 'பராமரிப்பு உத்தரவாதம்',
    'banking.supplyGuarantee': 'வழங்கல் உத்தரவாதம்',
    'banking.performanceBond': 'செயல்திறன் பிணை',
    'banking.advancePaymentBond': 'முன்பண பிணை',
    'banking.retentionMoneyBond': 'தக்க வைப்பு பண பிணை',
    'banking.warrantyBond': 'உத்தரவாத பிணை',
    'banking.maintenanceBond': 'பராமரிப்பு பிணை',
    'banking.supplyBond': 'வழங்கல் பிணை',
    'banking.city': 'நகரம்',
    'banking.district': 'மாவட்டம்',
    'banking.coordinates': 'ஆயங்கள்',
    'banking.tryAgain': 'மீண்டும் முயற்சிக்கவும்',
    'banking.detectingLocation': 'உங்கள் இடத்தை கண்டறிகிறது...',
    'banking.email': 'மின்னஞ்சல்',
    'banking.visitWebsite': 'வலைத்தளத்தை பார்வையிடவும்',
    'banking.interestRateLabel': 'வட்டி விகிதம்:',
    'banking.maxAmountLabel': 'அதிகபட்ச தொகை:',
    'banking.tenureLabel': 'காலம்:',
    'banking.note': 'குறிப்பு:',
    'banking.interestRatesNote': 'வட்டி விகிதங்கள் மற்றும் விதிமுறைகள் மாறக்கூடும். மிகவும் தற்போதைய தகவலுக்கு தொடர்புடைய வங்கிகளைத் தொடர்பு கொள்ளவும்.',
    'banking.governmentBenefits': 'அரசு நன்மைகள்:',
    'banking.governmentBenefitsNote': 'பல கடன்கள் அரசு மானியங்களுக்கு தகுதியுடையவை. தற்போதைய திட்டங்களுக்கு உங்கள் உள்ளூர் விவசாய அலுவலகத்தை சரிபார்க்கவும்.',
    
    // Bank names
    'banking.banks.tnGramaBank': 'தமிழ்நாடு கிராம வங்கி',
    'banking.banks.bankOfBaroda': 'பரோடா வங்கி',
    'banking.banks.hdfcBank': 'HDFC வங்கி',
    'banking.banks.paccs': 'முதன்மை விவசாய கூட்டுறவு கடன் சங்கங்கள் (PACCS)',
    
    // Lending
    'lending.title': 'சிறு கடன்',
    'lending.subtitle': 'தமிழ்நாடு விவசாயிகளுக்கான சமூக அடிப்படையிலான கடன் வட்டங்கள்',
    'lending.home': 'முகப்பு',
    'lending.circles': 'கடன் வட்டங்கள்',
    'lending.myLoans': 'எனது கடன்கள்',
    'lending.admin': 'நிர்வாகம்',
    'lending.welcomeTitle': 'AgroConnect சிறு கடனுக்கு வரவேற்கிறோம்',
    'lending.welcomeSubtitle': 'தமிழ்நாடு முழுவதும் உள்ள விவசாயிகளுடன் நம்பகமான கடன் வட்டங்களில் சேருங்கள்',
    'lending.joinCircle': 'வட்டத்தில் சேருங்கள்',
    'lending.applyLoan': 'கடனுக்கு விண்ணப்பிக்கவும்',
    'lending.viewLoans': 'எனது கடன்களை பார்க்கவும்',
    'lending.circlesAvailable': 'கிடைக்கும் கடன் வட்டங்கள்',
    'lending.membersOnline': 'ஆன்லைனில் உள்ள உறுப்பினர்கள்',
    'lending.totalLoans': 'மொத்த கடன்கள்',
    'lending.avgApprovalTime': 'சராசரி ஒப்புதல் நேரம்',
    'lending.hours': 'மணிநேரம்',
    'lending.exploreCircles': 'வட்டங்களை ஆராயுங்கள்',
    'lending.activeStatus': 'செயலில்',
    'lending.fullStatus': 'நிரம்பியது',
    'lending.newStatus': 'புதிய',
    'lending.members': 'உறுப்பினர்கள்',
    'lending.interestRate': 'வட்டி விகிதம்',
    'lending.loanRange': 'கடன் வரம்பு',
    'lending.completedLoans': 'முடிந்த கடன்கள்',
    'lending.trustScore': 'நம்பிக்கை மதிப்பீடு',
    'lending.memberContribution': 'உறுப்பினர் பங்களிப்பு',
    'lending.admin': 'நிர்வாகி',
    'lending.joinWhatsApp': 'WhatsApp குழுவில் சேருங்கள்',
    'lending.alreadyJoined': 'ஏற்கனவே சேர்ந்துள்ளீர்கள்',
    'lending.requestLoan': 'கடன் கோருங்கள்',
    'lending.pendingLoans': 'நிலுவையில் உள்ள கடன்கள்',
    'lending.approvedLoans': 'ஒப்புதல் பெற்ற கடன்கள்',
    'lending.repaidLoans': 'திருப்பிச் செலுத்திய கடன்கள்',
    'lending.amount': 'தொகை',
    'lending.purpose': 'நோக்கம்',
    'lending.status': 'நிலை',
    'lending.dueDate': 'நிலுவை தேதி',
    'lending.monthlyEMI': 'மாதாந்திர EMI',
    'lending.appliedDate': 'விண்ணப்பித்த தேதி',
    'lending.repaidDate': 'திருப்பிச் செலுத்திய தேதி',
    'lending.pending': 'நிலுவையில்',
    'lending.approved': 'ஒப்புதல்',
    'lending.repaid': 'திருப்பிச் செலுத்தியது',
    'lending.loanRequests': 'கடன் கோரிக்கைகள்',
    'lending.approveRequest': 'கோரிக்கையை ஒப்புதல்',
    'lending.rejectRequest': 'கோரிக்கையை நிராகரி',
    'lending.requestedBy': 'கோரியவர்',
    'lending.requestedOn': 'கோரிய தேதி',
    'lending.repaymentDuration': 'திருப்பிச் செலுத்தும் காலம்',
    'lending.applyForLoan': 'கடனுக்கு விண்ணப்பிக்கவும்',
    'lending.selectCircle': 'கடன் வட்டத்தை தேர்ந்தெடுக்கவும்',
    'lending.chooseCircle': 'கடன் வட்டத்தை தேர்வு செய்யுங்கள்',
    'lending.loanAmount': 'கடன் தொகை',
    'lending.enterAmount': 'தேவையான தொகையை உள்ளிடவும்',
    'lending.describePurpose': 'கடனை எவ்வாறு பயன்படுத்த திட்டமிட்டுள்ளீர்கள் என்பதை விவரிக்கவும்',
    'lending.selectDuration': 'காலத்தை தேர்ந்தெடுக்கவும்',
    'lending.months': 'மாதங்கள்',
    'lending.submitApplication': 'விண்ணப்பத்தை சமர்ப்பிக்கவும்',
    'lending.cancel': 'ரத்து செய்',
    'lending.successfullyJoined': 'வட்டத்தில் வெற்றிகரமாக சேர்ந்துள்ளீர்கள்! WhatsApp குழு திறக்கப்பட்டது.',
    'lending.applicationSubmitted': 'கடன் விண்ணப்பம் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!',
    'lending.close': 'மூடு',
    'lending.joinCircleDesc': 'உங்கள் சமூகத்தில் உள்ள விவசாயிகளுடன் இணைந்து கொள்ளுங்கள்',
    'lending.requestLoanDesc': 'மலிவான நிதியுதவியை விரைவாக பெறுங்கள்',
    'lending.buildTrust': 'நம்பிக்கை உருவாக்குங்கள்',
    'lending.buildTrustDesc': 'பொறுப்புள்ள கடன் மூலம் உங்கள் சமூகத்தை வளர்க்கவும்',
    'lending.activeCircles': 'செயலில் உள்ள வட்டங்கள்',
    'lending.totalMembers': 'மொத்த உறுப்பினர்கள்',
    'lending.loansCompleted': 'முடிந்த கடன்கள்',
    'lending.totalLending': 'மொத்த கடன்',
    'lending.availableCircles': 'கிடைக்கும் வட்டங்கள்',
    'lending.editProfile': 'சுயவிவரத்தை திருத்து',
    'lending.welcome': 'வரவேற்கிறோம்,',
    'lending.members': 'உறுப்பினர்கள்',
    'lending.interestRate': 'வட்டி விகிதம்',
    'lending.loanRange': 'கடன் வரம்பு',
    'lending.completedLoans': 'முடிந்த கடன்கள்',
    'lending.trustScore': 'நம்பிக்கை மதிப்பீடு',
    'lending.memberContribution': 'உறுப்பினர் பங்களிப்பு',
    'lending.admin': 'நிர்வாகி',
    'lending.joinWhatsApp': 'WhatsApp குழுவில் சேருங்கள்',
    'lending.alreadyJoined': 'ஏற்கனவே சேர்ந்துள்ளீர்கள்',
    'lending.circleFull': 'வட்டம் நிரம்பியது',
    'lending.joinedWhatsApp': 'WhatsApp குழுவில் சேர்ந்துள்ளீர்கள்',
    'lending.myLoans': 'எனது கடன்கள்',
    'lending.requestLoan': 'கடன் கோருங்கள்',
    'lending.selectCircle': 'வட்டத்தை தேர்ந்தெடுக்கவும்',
    'lending.chooseCircle': 'கடன் வட்டத்தை தேர்வு செய்யுங்கள்',
    'lending.loanAmount': 'கடன் தொகை',
    'lending.enterAmount': 'தேவையான தொகையை உள்ளிடவும்',
    'lending.describePurpose': 'கடனை எவ்வாறு பயன்படுத்த திட்டமிட்டுள்ளீர்கள் என்பதை விவரிக்கவும்',
    'lending.selectDuration': 'காலத்தை தேர்ந்தெடுக்கவும்',
    'lending.submitApplication': 'விண்ணப்பத்தை சமர்ப்பிக்கவும்',
    'lending.cancel': 'ரத்து செய்',
    'lending.appliedOn': 'விண்ணப்பித்த தேதி',
    'lending.repaidOn': 'திருப்பிச் செலுத்திய தேதி',
    'lending.dueDate': 'நிலுவை தேதி',
    'lending.monthlyEMI': 'மாதாந்திர EMI',
    'lending.adminPanel': 'நிர்வாக பலகை',
    'lending.pendingLoanRequests': 'நிலுவையில் உள்ள கடன் கோரிக்கைகள்',
    'lending.from': 'கோரியவர்',
    'lending.purpose': 'நோக்கம்',
    'lending.duration': 'காலம்',
    'lending.requestedOn': 'கோரிய தேதி',
    'lending.approve': 'ஒப்புதல்',
    'lending.reject': 'நிராகரி',
    'lending.noPendingRequests': 'நிலுவையில் உள்ள கடன் கோரிக்கைகள் இல்லை',
    'lending.checkBackLater': 'புதிய கோரிக்கைகளுக்கு பின்னர் சரிபார்க்கவும்',
    'lending.howMicroLendingWorks': 'சிறு கடன் எவ்வாறு செயல்படுகிறது',
    'lending.joinCircle': 'வட்டத்தில் சேருங்கள்',
    'lending.connectWithFarmers': 'உங்கள் சமூகத்தில் உள்ள விவசாயிகளுடன் இணைந்து கொள்ளுங்கள்',
    'lending.contribute': 'பங்களிப்பு',
    'lending.makeContribution': 'வட்டத்தின் கடன் நிதியில் ஒரு முறை பங்களிப்பு செய்யுங்கள்',
    'lending.requestLoan': 'கடன் கோருங்கள்',
    'lending.applyForLoans': 'தேவைப்படும் போது கடன்களுக்கு விண்ணப்பிக்கவும், வட்ட உறுப்பினர் ஒப்புதலுடன்',
    'lending.repayAndGrow': 'திருப்பிச் செலுத்தி வளர்ச்சி',
    'lending.repayOnTime': 'நம்பிக்கையை உருவாக்கி சமூக நிதியை வளர்ப்பதற்கு சரியான நேரத்தில் திருப்பிச் செலுத்துங்கள்',
    'lending.editProfile': 'சுயவிவரத்தை திருத்து',
    'lending.yourName': 'உங்கள் பெயர்',
    'lending.enterYourName': 'உங்கள் பெயரை உள்ளிடவும்',
    'lending.saveChanges': 'மாற்றங்களை சேமி',
    'lending.whatsAppMessageSent': 'WhatsApp செய்தி அனுப்பப்பட்டது!',
    'lending.loanRequestSent': 'உங்கள் கடன் கோரிக்கை WhatsApp மூலம் நிர்வாகிக்கு அனுப்பப்பட்டது',
    'lending.whatsAppGroupOpened': 'WhatsApp குழு திறக்கப்பட்டது!',
    'lending.joinGroupForLoanRequests': 'கடன் கோரிக்கைகளை அணுக குழுவில் சேருங்கள்',
    
    // Equipment
    'equipment.title': 'விவசாய கருவிகள்',
    'equipment.subtitle': 'உங்கள் பண்ணைக்கு நவீன கருவிகளை வாடகைக்கு எடுங்கள்',
    'equipment.rentNow': 'இப்போது வாடகைக்கு எடு',
    'equipment.addToCart': 'கார்டில் சேர்',
    'equipment.pricePerDay': 'ஒரு நாளுக்கு',
    
    // Forum
    'forum.title': 'சமூக மன்றம்',
    'forum.subtitle': 'அறிவை பகிர்ந்து விவசாயிகளுடன் இணைந்து கொள்ளுங்கள்',
    'forum.createPost': 'இடுகையை உருவாக்கு',
    'forum.search': 'இடுகைகளை தேடுங்கள்...',
    'forum.categories': 'வகைகள்',
    'forum.recent': 'சமீபத்திய',
    'forum.popular': 'பிரபலமான',
    'forum.like': 'விரும்பு',
    'forum.reply': 'பதில்',
    'forum.share': 'பகிர்',
    
    // Lending
    'lending.title': 'சிறு கடன்',
    'lending.subtitle': 'விவசாயிகளுக்கான சமூக அடிப்படையிலான கடன்',
    'lending.joinCircle': 'வட்டத்தில் சேர்',
    'lending.requestLoan': 'கடன் கோரி',
    'lending.myLoans': 'எனது கடன்கள்',
    'lending.admin': 'நிர்வாக பலகை',
    
    // Expenses
    'expenses.title': 'செலவு கண்காணிப்பு',
    'expenses.subtitle': 'உங்கள் விவசாய செலவுகளை கண்காணியுங்கள்',
    'expenses.addExpense': 'செலவை சேர்',
    'expenses.category': 'வகை',
    'expenses.amount': 'தொகை',
    'expenses.description': 'விளக்கம்',
    'expenses.date': 'தேதி',
    'expenses.recentExpenses': 'சமீபத்திய செலவுகள்',
    'expenses.totalExpenses': 'மொத்த செலவுகள்',
    
    // Common
    'common.loading': 'ஏற்றுகிறது...',
    'common.error': 'பிழை',
    'common.success': 'வெற்றி',
    'common.cancel': 'ரத்து செய்',
    'common.save': 'சேமி',
    'common.delete': 'நீக்கு',
    'common.edit': 'திருத்து',
    'common.view': 'காண்க',
    'common.close': 'மூடு',
    'common.submit': 'சமர்ப்பி',
    'common.back': 'பின்',
    'common.next': 'அடுத்து',
    'common.previous': 'முந்தைய',
    'common.note': 'குறிப்பு',
    'common.available': 'கிடைக்கும்',
    
    // Schemes page
    'schemes.title': 'அரசு திட்டங்கள்',
    'schemes.subtitle': 'தமிழ்நாடு விவசாய திட்டங்கள் மற்றும் நன்மைகளை அணுகுங்கள்',
    'schemes.searchPlaceholder': 'திட்டங்களை தேடுங்கள்...',
    'schemes.filterAll': 'அனைத்து திட்டங்கள்',
    'schemes.filterActive': 'செயலில்',
    'schemes.filterUpcoming': 'வரவிருக்கும்',
    'schemes.filterExpired': 'காலாவதியான',
    'schemes.applyNow': 'இப்போது விண்ணப்பிக்கவும்',
    'schemes.viewDetails': 'விவரங்களை பார்க்கவும்',
    'schemes.eligibility': 'தகுதி',
    'schemes.benefits': 'நன்மைகள்',
    'schemes.deadline': 'விண்ணப்ப கடைசி தேதி',
    'schemes.status': 'நிலை',
    'schemes.amount': 'தொகை',
    'schemes.category': 'வகை',
    'schemes.agricultural': 'விவசாய',
    'schemes.livestock': 'கால்நடை',
    'schemes.irrigation': 'பாசனம்',
    'schemes.equipment': 'கருவிகள்',
    'schemes.insurance': 'காப்பீடு',
    'schemes.loan': 'கடன்',
    'schemes.subsidy': 'மானியம்',
    'schemes.training': 'பயிற்சி',
    'schemes.other': 'மற்றவை',
    
    // Forum page
    'forum.title': 'சமூக மன்றம்',
    'forum.subtitle': 'விவசாயிகளுடன் இணைந்து அறிவை பகிர்ந்து கொள்ளுங்கள்',
    'forum.createPost': 'இடுகையை உருவாக்கு',
    'forum.searchPlaceholder': 'இடுகைகளை தேடுங்கள்...',
    'forum.categories': 'வகைகள்',
    'forum.allPosts': 'அனைத்து இடுகைகள்',
    'forum.myPosts': 'எனது இடுகைகள்',
    'forum.popular': 'பிரபலமான',
    'forum.recent': 'சமீபத்திய',
    'forum.trending': 'பிரபலமாக வரும்',
    'forum.like': 'விரும்பு',
    'forum.reply': 'பதில்',
    'forum.share': 'பகிர்',
    'forum.report': 'புகார்',
    'forum.edit': 'திருத்து',
    'forum.delete': 'நீக்கு',
    'forum.postTitle': 'இடுகை தலைப்பு',
    'forum.postContent': 'உங்கள் இடுகையை எழுதுங்கள்...',
    'forum.selectCategory': 'வகையை தேர்ந்தெடுக்கவும்',
    'forum.addImage': 'படத்தை சேர்க்கவும்',
    'forum.publish': 'வெளியிடு',
    'forum.cancel': 'ரத்து செய்',
    'forum.replies': 'பதில்கள்',
    'forum.views': 'பார்வைகள்',
    'forum.postedBy': 'இடுகையிட்டவர்',
    'forum.ago': 'முன்',
    'forum.hours': 'மணி நேரங்கள்',
    'forum.days': 'நாட்கள்',
    'forum.weeks': 'வாரங்கள்',
    'forum.months': 'மாதங்கள்',
    'forum.years': 'ஆண்டுகள்',
    'forum.writeReply': 'பதில் எழுதுங்கள்...',
    'forum.submitReply': 'பதிலை சமர்ப்பிக்கவும்',
    'forum.noPosts': 'இடுகைகள் எதுவும் கிடைக்கவில்லை',
    'forum.loadMore': 'மேலும் ஏற்று',
    
    // Banking page
    'banking.title': 'வங்கி சேவைகள்',
    'banking.subtitle': 'விவசாய கடன்கள், காப்பீடு மற்றும் நிதி சேவைகள்',
    'banking.loans': 'கடன்கள்',
    'banking.insurance': 'காப்பீடு',
    'banking.savings': 'சேமிப்பு',
    'banking.investments': 'முதலீடுகள்',
    'banking.applyLoan': 'கடனுக்கு விண்ணப்பிக்கவும்',
    'banking.getInsurance': 'காப்பீடு பெறுங்கள்',
    'banking.openAccount': 'கணக்கை திறக்கவும்',
    'banking.interestRate': 'வட்டி விகிதம்',
    'banking.tenure': 'காலம்',
    'banking.maxAmount': 'அதிகபட்ச தொகை',
    'banking.processingFee': 'செயலாக்க கட்டணம்',
    'banking.eligibility': 'தகுதி',
    'banking.documents': 'தேவையான ஆவணங்கள்',
    'banking.applyNow': 'இப்போது விண்ணப்பிக்கவும்',
    'banking.learnMore': 'மேலும் அறிய',
    'banking.agriculturalLoan': 'விவசாய கடன்',
    'banking.equipmentLoan': 'கருவி கடன்',
    'banking.cropInsurance': 'பயிர் காப்பீடு',
    'banking.livestockInsurance': 'கால்நடை காப்பீடு',
    'banking.savingsAccount': 'சேமிப்பு கணக்கு',
    'banking.currentAccount': 'நடப்பு கணக்கு',
    'banking.fixedDeposit': 'நிலையான வைப்பு',
    'banking.recurringDeposit': 'தொடர்ச்சியான வைப்பு',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('agroconnect-language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ta')) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when changed
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('agroconnect-language', lang);
  };

  // Translation function
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
